plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    // AGP 9.0+ 内置 Kotlin 支持：org.jetbrains.kotlin.android 不再需要单独应用
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "com.bail.lspfrifa"
    // Miuix 0.9.3 与 libxposed 102.0.0 的 AAR metadata 要求 API 37。
    compileSdk = 37
    // 显式指定 NDK：避免 AGP 回退到其内置默认版本 (27.0.12077973)
    ndkVersion = "28.2.13676358"
    // compileSdk 与 build-tools 可独立设置；35.0.1 内置 arm64 aidl，37.0.0 版本是 x86_64，不能在本机执行。
    buildToolsVersion = "35.0.1"

    defaultConfig {
        applicationId = "com.bail.lspfrifa"
        // minSdk 26：保持现有 LSPosed 宿主兼容基线（底栏已改轻量自绘，无需 blur 库的 API33 要求）
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        ndk {
            // P0-1（2026-10-06）：仅 arm64-v8a —— 砍掉 32 位分支。
            // 依据（APK 实测）：armeabi-v7a/libgumjs_bridge.so 压缩后仍占 27.19 MB，
            // 为全包 87 MB 的 32%；而验证环境（小米 23013RK75C / Android 15）为 arm64，
            // 32 位设备在 A15 时代已无实际目标 —— 纯负担。
            // devkit 的 armeabi-v7a 目录**保留在源码树**（未删），需要时把 ABI 加回本行即可。
            abiFilters += listOf("arm64-v8a")
        }

        externalNativeBuild {
            cmake {
                cppFlags += "-std=c++17"
                arguments += "-DANDROID_STL=c++_static"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            // t14：RV2IDE usr/bin/cmake 环境失效 → SDK 3.22.1 重新替换为 4.1.2 内容（见构建说明）
            version = "3.22.1"
        }
    }

    buildFeatures {
        viewBinding = true
        aidl = true
        compose = true
    }

    // P1（2026-10-06）：启用 R8 —— dex 体积从 17.67 MB 的根因是「无 buildTypes 块」。
    // 第一性原理：dex 里绝大部分是未被直接引用的库代码（Compose/Miuix/sora-editor/tm4e）
    // 的类与方法，R8 的 shrink（可达性分析）+ optimize（内联/类合并）+ obfuscate（重命名）
    // 三者中，**shrink 是体积收益的主力**，obfuscate 只影响常量池里的标识符长度。
    //
    // 风险控制（依据实核，见 app/proguard-rules.pro 顶部注释）：
    //   1. libxposed 入口按 META-INF/xposed/java_init.list 里的**硬编码字符串**反射加载
    //   2. 6 个 JNI 方法名即 C 符号名（Java_com_bail_lspfrifa_xposed_GumJsBridge_nativeXxx）
    //   3. AIDL 跨进程按接口全名 + 事务方法名通信，两侧混淆结果必须一致
    //   以上三类已全部写入 keep 规则。
    //
    // 注意：本模块的 release 变体**不签名**（未配置 signingConfig）——
    //       `assembleRelease` 产出 `app-release-unsigned.apk`，需手动签名或用 debug 变体验证。
    //       若只想验证 R8 效果而不想处理签名，可临时用 `isMinifyEnabled = true` 打在 debug 上。
    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
        // debug 保持不混淆：真机验证阶段需要可读栈 + 快速增量编译。
        // R8 的效果只在 release 变体上体现（体积收益在发布包上看）。
        debug {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        // t5：sora-editor language-textmate 契约要求 API<33 开启 core-library desugaring（宿主 minSdk 26<33）
        isCoreLibraryDesugaringEnabled = true
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)

    // Compose Multiplatform 1.11.1 Android artifacts，和 Miuix 0.9.3 对齐
    implementation(libs.compose.foundation)
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.icons.extended)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.viewmodel.compose)
    implementation(libs.kotlinx.coroutines.android)
    // Compose Navigation：项目模块路由（主页面 / 选择项目全屏页 / 项目详情）
    implementation(libs.androidx.navigation.compose)
    debugImplementation("org.jetbrains.compose.ui:ui-tooling:1.12.0-rc01")

    // Miuix 0.9.4-rc01 原生模块
    implementation(libs.miuix.ui)
    implementation(libs.miuix.preference)
    // miuix-blur（玻璃拟态）：AAR minSdk33 已用 <uses-sdk tools:overrideLibrary> 正确放行（官方方式）；
    // 运行时 isRuntimeShaderSupported gate 保证 API<33 降级纯色、零崩溃风险
    implementation(libs.miuix.blur)
    // libxposed 现代规范（阶段二使用；compileOnly：运行时由 LSPosed 框架提供）
    compileOnly("io.github.libxposed:api:102.0.0")
    // 模块宿主 App 通过该服务与 LSPosed 通信，用于真实激活状态、scope 等
    implementation("io.github.libxposed:service:102.0.0")

    // sora-editor 0.23.6：详情页脚本代码编辑器（替换 Miuix TextField；View 体系 CodeEditor，零 Compose 依赖）
    implementation(libs.sora.editor)
    // sora-editor TextMate 语法高亮（JS grammar + VSCode 主题资源；runtime 传递 joni/jcodings/gson/snakeyaml-engine 等）
    implementation(libs.sora.textmate)
    // t5：language-textmate API<33 需要 core-library desugaring（2.1.5 = google maven 最新稳定）
    coreLibraryDesugaring(libs.desugar.jdk.libs)
    // Monet 主题（材料3 动态色：dynamicLightColorScheme/dynamicDarkColorScheme 读取系统壁纸色）
    // ——用户明确：引入 M3 的目的 = 支持 Monet 主题（非组件仿制）
    implementation(libs.compose.material3)

}